# Spring boot settings
spring.application.name=@project.name@
spring.application.version=@project.version@
application.desc=@project.desc@


# Caffeine Settings
caffeine.cache-names=countries,distributions,mirrors


# launchPad settings
launch-pad.base-url=https://api.launchpad.net/devel