# Spring boot settings
spring.application.name=@project.name@
spring.application.version=@project.version@
application.desc=@project.desc@


# Caffeine Settings
caffeine.cache-names=countries,distributions,mirrors


# launchPad settings
launch-pad.base-url=https://api.launchpad.net/devel
launch-pad.mirror-type=Archive
launch-pad.mirror-ws-op=getBestMirrorsForCountry


# Logging Settings
## Console logging
logging.level.org.khu=DEBUG

## File logging
logging.file.name=logs/application.log

## Pattern
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n

## Optional rotation
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB